export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 299,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Fried Chicken',
    price: 199,
    cookTime: '20-30',
    favorite: true,
    origins: ['USA', 'UK'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 149,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },

  {
    id: '5',
    name: 'Chicken Soup',
    price: 99,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
 
  {
    id: '7',
    name: 'Biryani',
    price: 150,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.8,
    imageUrl: 'food-7.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '8',
    name: 'Masala Dosa',
    price: 80,
    cookTime: '20-30',
    favorite: true,
    origins: ['india'],
    stars: 4.7,
    imageUrl: 'food-8.jpg',
    tags: ['FastFood', 'Breakfast'],
  },
  {
    id: '9',
    name: 'Samosa',
    price: 20,
    cookTime: '15-25',
    favorite: false,
    origins: ['india'],
    stars: 4.2,
    imageUrl: 'food-9.jpg',
    tags: ['FastFood', 'Snack'],
  },
  {
    id: '10',
    name: 'Chole Bhature',
    price: 80,
    cookTime: '25-35',
    favorite: true,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'food-10.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '11',
    name: 'Palak Paneer',
    price: 150,
    cookTime: '25-35',
    favorite: false,
    origins: ['india'],
    stars: 4.6,
    imageUrl: 'food-11.jpg',
    tags: ['SlowFood', 'Dinner'],
  },
  {
    id: '12',
    name: 'Dhokla',
    price: 40,
    cookTime: '15-20',
    favorite: false,
    origins: ['india'],
    stars: 4.0,
    imageUrl: 'food-12.jpg',
    tags: ['FastFood', 'Breakfast'],
  },
  {
    id: '13',
    name: 'Rajma Chawal',
    price: 129,
    cookTime: '30-40',
    favorite: true,
    origins: ['india'],
    stars: 4.3,
    imageUrl: 'food-13.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '14',
    name: 'Gulab Jamun',
    price: 30,
    cookTime: '10-15',
    favorite: false,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'food-14.jpg',
    tags: ['Dessert', 'Snack'],
  },
  {
    id: '15',
    name: 'Masala Chai',
    price: 20,
    cookTime: '5-10',
    favorite: true,
    origins: ['india'],
    stars: 4.8,
    imageUrl: 'food-15.jpg',
    tags: ['Beverage', 'Breakfast'],
  },
  {
    id: '16',
    name: 'Pani Puri',
    price: 35,
    cookTime: '10-15',
    favorite: false,
    origins: ['india'],
    stars: 4.2,
    imageUrl: 'food-16.jpg',
    tags: ['StreetFood', 'Snack'],
  },
  {
    id: '17',
    name: 'Butter Chicken',
    price: 180,
    cookTime: '30-40',
    favorite: true,
    origins: ['india'],
    stars: 4.7,
    imageUrl: 'food-17.jpg',
    tags: ['SlowFood', 'Dinner'],
  },
  {
    id: '18',
    name: 'Jalebi',
    price: 45,
    cookTime: '15-20',
    favorite: false,
    origins: ['india'],
    stars: 4.4,
    imageUrl: 'food-18.jpg',
    tags: ['Dessert', 'Snack'],
  },
  {
    id: '19',
    name: 'Aloo Paratha',
    price: 50,
    cookTime: '15-25',
    favorite: true,
    origins: ['india'],
    stars: 4.6,
    imageUrl: 'food-19.jpg',
    tags: ['Breakfast', 'Lunch'],
  },
  {
    id: '20',
    name: 'Tandoori Chicken',
    price: 180,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'food-20.jpg',
    tags: ['SlowFood', 'Dinner'],
  },
 
  {
    id: '21',
    name: 'Paneer Butter Masala',
    price: 150,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'food-21.jpg',
    tags: ['SlowFood', 'Dinner'],
  },
];

// Tag data
export const sample_tags = [
  { name: 'All', count: 26 },
  { name: 'FastFood', count: 10 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 8 },
  { name: 'SlowFood', count: 8 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
  { name: 'Breakfast', count: 4 },
  { name: 'Snack', count: 4 },
  { name: 'Dessert', count: 3 },
  { name: 'Beverage', count: 1 },
  { name: 'StreetFood', count: 1 },
];

// User data
export const sample_users = [
  {
    id: 1,
    name: 'Sheshank',
    email: 'sri9848d@gmail.com',
    password: '12345',
    address: 'Khammam',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Rajinikanth',
    email: 'rajini@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
  {
    id: 3,
    name: 'Ethunus',
    email: 'ethunus@gmail.com',
    password: 'ethnus',
    address: 'Coimbatore',
    isAdmin: false,
  },
];

